name: CI/CD - Develop
on:
  push:
    branches: [develop]
jobs:
  test:
    runs-on: macos-13
    name: Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test code
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck
