name: CI/CD - Develop
on:
  push:
    branches: [develop]
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17
          cache: gradle
      - name: Test code
        run: ./gradlew connectedAndroidTest
