name: CI/CD - Develop
on:
  push:
    branches: [develop]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: Deploying
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - name: Generate local.properties
        run: echo RELEASE_BASE_URL="${{ secrets.BASE_URL }}" > ./local.properties
      - name: Generate google-services.json
        run: |
          cat /home/runner/work/Temzone-Android/Temzone-Android/app/src/release/google-services.json
          echo $${{ secrets.GOOGLE_SERVICES }} > /home/runner/work/Temzone-Android/Temzone-Android/app/src/release/google-services.json
      - name: Build project
        run: ./gradlew build
      - name: Generate artifacts
        run: ./gradlew assemble
